### ISSUE TITLE
Add to docker-compose and use it

### ISSUE THREAD

**Issue by ghost** [Plattar/python-xrutils#2]
I'm quite new to docker and I'm looking for a container that does exactly what yours do!

**disclaimer:** I understand this might be out of the scope of the support you give for this container. If it is indeed out of the scope, please go ahead and close this issue directly.

What I'm trying to do here is to add your container to my docker-compose and then be able to generate a usd with a file from my API container and have its usdz on my API disk container

So far I have something looking like this:

```
services:
  usd:
    image: plattar/python-xrutils

  web:
    image: api-dev:1.0.0
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    ports:
      - "3000:3000"
    command: rails server -b 0.0.0.0
```

But I'm quite lost when it comes to "how to connect both" and what command to use on my web in order to reach usd container.

Any idea?
